apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-whitelist-bot
  labels:
    app: discord-whitelist-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-whitelist-bot
  template:
    metadata:
      labels:
        app: discord-whitelist-bot
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: bot
          image: marongt123/bedrock-discord-whitelist:latest
          imagePullPolicy: Always
          env:
            - name: BOT_TOKEN
            - name: APPLY_CHANNEL
            - name: APPROVE_CHANNEL
            - name: ADMIN_ROLE
            - name: WHITELIST_FILE
            - name: ALLOWLIST_FILE
          volumeMounts:
            - name: whitelist-data
              mountPath: /app
      volumes:
        - name: whitelist-data
          emptyDir: {}

