apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-whitelist-bot
  labels:
    app: discord-whitelist-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-whitelist-bot
  template:
    metadata:
      labels:
        app: discord-whitelist-bot
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000

      initContainers:
        - name: render-config
          image: busybox
          command:
            - sh
            - -c
            - |
              envsubst < /tmpl/config.yaml.tmpl > /config/config.yaml
          envFrom:
            - secretRef:
                name: discordbot-secret
          volumeMounts:
            - name: config
              mountPath: /config
            - name: discordbot-config
              mountPath: /tmpl
              
      containers:
        - name: bot
          image: marongt123/bedrock-discord-whitelist:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: CFG_BOT_TOKEN
            - name: CFG_SERVER_APPLY_CHANNEL
            - name: CFG_SERVER_APPROVE_CHANNEL
            - name: CFG_SERVER_ADMIN_ROLE
            - name: CFG_MINECRAFT_WHITELIST_FILE
            - name: CFG_MINECRAFT_ALLOWLIST_FILE
          volumeMounts:
            - name: whitelist-data
              mountPath: /data
            - name: config
              mountPath: /app/config.yaml
              subPath: config.yaml
      volumes:
        - name: whitelist-data
          emptyDir: {}
        - name: config
          emptyDir: {}
        - name: config-templete
          configMap:
            name: discordbot-config
