apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: discord-bot-binding
subjects:
- kind: ServiceAccount
  name: discord-bot
roleRef:
  kind: Role
  name: discord-bot-role
  apiGroup: rbac.authorization.k8s.io
