bot:
  token: "${DISCORD_BOT_TOKEN}"

server:
  name: example_servername
  description: "discordlog_name"
  discord_guild: "${DISCORD_SERVER_ID}"
  apply_channel: "${DISCORD_APPLY_CHANNELID}"
  approve_channel: "${DISCORD_APPROVE_CHANNELID}"
  admin_role: "${DISCORD_ADMINROLEID}"

  whitelist_file: "whitelist.json"
  allowlist_file: "allowlist.json"

  bds_reload: "kubectl exec -n mc-bedrock bedrock-s1-0 -- screen -S bedrock -X stuff 'allowlist reload\n'"
